import type { NavItem } from "prui/app"
import { BookOpenIcon, BookMarkedIcon, PaletteIcon, LayersIcon } from "./nav-icons"

export const nav: NavItem[] = [
  { label: "Introduction", href: "/", icon: BookOpenIcon },
  {
    label: "Guides",
    icon: BookMarkedIcon,
    items: [
      { label: "Installation", href: "/guides/installation" },
      { label: "Progressive adoption", href: "/guides/adoption" },
      { label: "Agents", href: "/agents" },
      { label: "Design tokens", href: "/guides/design-tokens" },
      { label: "Architecture", href: "/guides/architecture" },
      { label: "Accessibility", href: "/guides/accessibility" },
      { label: "SSR", href: "/guides/ssr" },
      { label: "Performance", href: "/guides/performance" },
      { label: "i18n & RTL", href: "/guides/i18n" },
      { label: "Changelog", href: "/changelog" },
      { label: "Migration guide", href: "/migration" },
    ],
  },
  {
    label: "Appearance",
    icon: PaletteIcon,
    items: [
      { label: "Icons", href: "/icons" },
      { label: "Layouts", href: "/layouts" },
      { label: "Theming", href: "/theming" },
      { label: "Theme builder", href: "/theme-builder" },
    ],
  },
  {
    label: "Components",
    icon: LayersIcon,
    items: [
      { label: "Primitives", heading: true },
      { label: "Button", href: "/components/button" },
      { label: "Input", href: "/components/input" },
      { label: "Textarea", href: "/components/textarea" },
      { label: "Select", href: "/components/select" },
      { label: "Switch", href: "/components/switch" },
      { label: "Tabs", href: "/components/tabs" },
      { label: "Badge", href: "/components/badge" },
      { label: "Card", href: "/components/card" },
      { label: "Avatar", href: "/components/avatar" },
      { label: "Label", href: "/components/label" },
      { label: "Separator", href: "/components/separator" },
      { label: "Scroll area", href: "/components/scroll-area" },
      { label: "Dialog", href: "/components/dialog" },
      { label: "Dropdown", href: "/components/dropdown" },
      { label: "Modal", href: "/components/modal" },
      { label: "Alert", href: "/components/alert" },
      { label: "Toast", href: "/components/toast" },
      { label: "Progress", href: "/components/progress" },
      { label: "Skeleton", href: "/components/skeleton" },
      { label: "Spinner", href: "/components/spinner" },
      { label: "Tooltip", href: "/components/tooltip" },
      { label: "Popover", href: "/components/popover" },
      { label: "Checkbox", href: "/components/checkbox" },
      { label: "Radio", href: "/components/radio" },
      { label: "Combobox", href: "/components/combobox" },
      { label: "FileUpload", href: "/components/file-upload" },
      { label: "Accordion", href: "/components/accordion" },
      { label: "Breadcrumb", href: "/components/breadcrumb" },
      { label: "Tree view", href: "/components/tree-view" },
      { label: "Timeline", href: "/components/timeline" },
      { label: "Drawer", href: "/components/drawer" },
      { label: "Sheet", href: "/components/sheet" },
      { label: "Calendar", href: "/components/calendar" },
      { label: "DatePicker", href: "/components/date-picker" },
      { label: "DateRangePicker", href: "/components/date-range-picker" },
      { label: "TimePicker", href: "/components/time-picker" },
      { label: "TimeRangePicker", href: "/components/time-range-picker" },
      { label: "Shell & data", heading: true },
      { label: "App layer", href: "/app-layer" },
      { label: "DataTable", href: "/components/data-table" },
      { label: "Resource", href: "/resources" },
      { label: "Forms", href: "/forms" },
      { label: "Pre-made pages", href: "/pages-doc" },
    ],
  },
]
